-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgH8Ky6jmVJer0YHfX
Ik55/C+QggPX7OBgTdAfsIILyyCgCgYIKoZIzj0DAQehRANCAATPIrm3HpN/Wz9O
n0DMs3iu4d6CccPYSi9EinSLoNY/+tUjq35uf62oVYHSVBNEkngS6U93WMLIdvYg
VpAzYkpU
-----END PRIVATE KEY-----